<<<<<<< HEAD
dados: mtcars.csv
metodo: lasso
variaveis:
  Resposta:
    "x1": mpg
    "x2": hp
    "x3": wt
  Preditoras:
    "y": qsec
=======
dados: iris.csv
metodo: linear
variaveis:
  Resposta:
    "x1": Sepal.Length
    "x2": Sepal.Width
    "x3": Petal.Length
  Preditoras:
    "y": Petal.Width
>>>>>>> 4f6a844d7b49f2f635109e061a321f174c70657d
